apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod # Tên của Pod
  labels:
    app: mysql  # Nhãn để nhận diện Pod
spec:
  containers:
    - name: mysql   # Tên container tự đặt
      image: mysql:8.0  # Sử dụng phiên bản MySQL 8.0
      ports:
        - containerPort: 3306 # Cổng mặc định của MySQL
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret  # Tên của Secret chứa mật khẩu root
              key: mysql-root-password  # Khóa trong Secret
        - name: MYSQL_DATABASE  # Tên cơ sở dữ liệu khởi tạo
          value: wordpress  # Tạo cơ sở dữ liệu có tên 'wordpress'
        - name: MYSQL_USER # Tên người dùng mới
          value: wpuser # Tạo người dùng 'wpuser'
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret  # Tên của Secret chứa mật khẩu người dùng
              key: mysql-user-password  # Khóa trong Secret
      volumeMounts:
        - name: mysql-storage # Gắn volume vào thư mục dữ liệu của MySQL
          mountPath: /var/lib/mysql
  volumes:
    - name: mysql-storage   # Sử dụng emptyDir cho mục đích demo dữ liệu sẽ bị mất khi Pod bị xóa
      emptyDir: {}
